apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.appName }}-db-claim0
spec:
  accessModes:
  - ReadWriteOnce
  {{- if .Values.db.storage.class }}
  storageClassName: {{ .Values.db.storage.class }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.db.storage.capacity }}
