{{ if eq .Values.istio.enabled true }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.appName }}-seatable
spec:
  hosts:
  - {{ .Values.fqdn }}
  gateways:
  - {{ .Values.appName }}-seatable-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: {{ .Values.appName }}-seatable
        port:
          number: 80
{{ end }}
