apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.appName }}-seatable-claim0
spec:
  accessModes:
  - ReadWriteOnce
  {{- if .Values.db.storage.class }}
  storageClassName: {{ .Values.db.storage.class }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.app.storage.capacity }}
status: {}
